#!/bin/sh
xset r rate 300 50 &
xmodmap -e "clear Lock" &
picom --experimental-backends &
xmodmap -e "keysym Caps_Lock = Escape" &
xmodmap -e "keysym Menu = Super_R" &
xrdb -merge ~/.config/X11/Xresources &
exec bspwm
