abbr vim 'vim -i NONE'
abbr wget 'wget --hsts-file "$XDG_CACHE_HOME"/wget-hsts'
abbr grep 'grep --color=always'
abbr weechat 'weechat -d "$XDG_CONFIG_HOME"/weechat'
abbr yarn 'yarn --use-yarnrc "$XDG_CONFIG_HOME"/yarn/config'
abbr mbsync 'mbsync -c "$XDG_CONFIG_HOME"/isync/mbsyncrc'
abbr netbeans 'netbeans --userdir "${XDG_CONFIG_HOME}"/netbeans'
abbr svn 'svn --config-dir $XDG_CONFIG_HOME/subversion'
abbr adb 'HOME="$XDG_DATA_HOME"/android adb'
abbr dosbox 'dosbox -conf "$XDG_CONFIG_HOME"/dosbox/dosbox.conf'
