# bashrc is in XDG_CONFIG_HOME/bash/bashrc thanks to this snippet in /etc/bash.bashrc
# if [ -s "${XDG_CONFIG_HOME:-$HOME/.config}/bash/bashrc" ]; then
#  . "${XDG_CONFIG_HOME:-$HOME/.config}/bash/bashrc"
# fi
#

# declaring defaults

export EDITOR="nvim"
#export STATUSBAR="waybar"
export VIDEO="mpv"
export IMAGE="nsxiv"
export COLORTERM="truecolor"
export PAGER="less"
export WM="COSMIC"
export OPENER="mimeo"
export VISUAL="nvim"
export READER="zathura"
export TERMINAL="kitty"
export BROWSER="firefox"
export DIFFPROG="nvim -d"

# Adds `~/.local/bin` to $PATH

export PATH="/usr/local/bin:$HOME/.local/bin:/usr/bin/vendor_perl:$PATH"

# ~/ Clean-up:

export XDG_CONFIG_HOME="$HOME/.config"
export NOTMUCH_CONFIG=""$XDG_CONFIG_HOME"/notmuch/notmuchrc"
export NPM_CONFIG_USERCONFIG=""$XDG_CONFIG_HOME"/npm/npmrc"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XINITRC=""$XDG_CONFIG_HOME"/X11/xinitrc"
export GTK2_RC_FILES=""$XDG_CONFIG_HOME"/gtk-2.0/gtkrc"
export GOPATH=""$XDG_DATA_HOME"/go"
export CARGO_HOME=""$XDG_DATA_HOME"/cargo"
export PASSWORD_STORE_DIR=""$XDG_DATA_HOME"/pass"
export TERMINFO=""$XDG_DATA_HOME"/terminfo"
export TERMINFO_DIRS=""$XDG_DATA_HOME"/terminfo:/usr/share/terminfo"
#export XAUTHORITY=""$XDG_RUNTIME_DIR"/Xauthority"
export GRADLE_USER_HOME=""$XDG_DATA_HOME"/gradle"
export WEECHAT_HOME=""$XDG_CONFIG_HOME"/weechat"
export ANDROID_USER_HOME="$XDG_DATA_HOME"/android
export ANDROID_HOME="$XDG_DATA_HOME"/android/sdk
export ADB_VENDOR_KEYS=""$XDG_DATA_HOME"/android/adbkey"
export PYTHONSTARTUP="${XDG_CONFIG_HOME}/python/pythonrc"
#export GNUPGHOME=""$XDG_DATA_HOME"/gnupg"
export WINEPREFIX=""$XDG_DATA_HOME"/wine"
export JUPYTER_PLATFORM_DIRS=""$XDG_CONFIG_HOME"/jupyter"
export W3M_DIR="$XDG_STATE_HOME/w3m"
export PARALLEL_HOME=""$XDG_CONFIG_HOME"/parallel"
export KERAS_HOME=""$XDG_CONFIG_HOME"/keras"
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export REPO_CONFIG_DIR="$XDG_CONFIG_HOME"
export SQLITE_HISTORY="$XDG_CACHE_HOME"/sqlite_history
export DVDCSS_CACHE="$XDG_DATA_HOME"/dvdcss
export HISTFILE="$XDG_STATE_HOME"/bash/history

#other miscellaneous programs

export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export ASAN_OPTIONS="log_path=asan.log"

# QT Config

#export QT_STYLE_OVERRIDE="kvantum"
export QT_QPA_PLATFORMTHEME="qt5ct"

#less config

export LESSHISTFILE="-"

# colored man pages

export LESS_TERMCAP_md=$'\e[01;31m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;44;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[01;32m'

#nnn

export NNN_FIFO="/tmp/nnn.fifo"
export NNN_HELP="fortune"
export NNN_PLUG='p:preview-tui;x:!chmod +x $nnn'
#export NNN_OPENER="swallow xdg-open"
export NNN_OPENER="xdg-open"
export NNN_BMS="g:~/dl/git/;d:~/dl/;m:~/mus/;s:~/.local/share/stuff;r:~/.local/share/rtorrent;h:~/.local/share/mount;o:~/docs/"
export NNN_ARCHIVE="\\.(7z|a|ace|alz|arc|arj|bz|bz2|cab|cpio|deb|gz|jar|lha|lz|lzh|lzma|lzo|rar|rpm|rz|t7z|tar|tbz|tbz2|tgz|tlz|txz|tZ|tzo|war|xpi|xz|Z|zip)$"
export NNN_COLORS='1234'
export NNN_FCOLORS='c1e2272e006033f7c6d6abc4'
export LANG=en_IN.UTF-8


# IBus support

#export GTK_IM_MODULE=ibus
#export GLFW_IM_MODULE=ibus
#export QT_IM_MODULE=ibus
#export XMODIFIERS=@im=ibus

# Wayland

export BEMENU_OPTS="--fn 'Fira Code 16' --fb #4C566Ae6 --ff #ECEFF4 --nb #4C566Ae6 --nf #ECEFF4 --tb #4C566Ae6 --hb #4C566Ae6 --tf #BF616A --hf #EBCB8B --nf #ECEFF4 --af #ECEFF4 --ab #4C566Ae6"
export SDL_VIDEODRIVER="wayland,x11"
export _JAVA_AWT_WM_NONREPARENTING=1
export XDG_CURRENT_DESKTOP=COSMIC
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=COSMIC
export QT_QPA_PLATFORM="wayland;xcb"
export GDK_BACKEND="wayland,x11"
export MOZ_ENABLE_WAYLAND=1
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_WAYLAND_DISABLE_WINDOW_DECORATION=1
export GTK_THEME="Adw-dark"


# aliases

## misc niceties

alias np="ncmpcpp"
alias rt="rtorrent"
alias ls='lsd '
alias nb="newsboat"
alias d="git --git-dir=$HOME/dl/git/dotfiles/ --work-tree=$HOME "
alias nm="neomutt"
alias pb="podboat"
alias nv="nvim"

## program aliases due to xdg, etc

alias vim="vim -i NONE"
alias wget='wget --hsts-file="$XDG_CACHE_HOME"/wget-hsts'
alias grep="grep --color=always"
alias cp="advcp -gv"
alias mv="advmv -gv"
alias weechat='weechat -d "$XDG_CONFIG_HOME"/weechat'
alias mbsync='mbsync -c "$XDG_CONFIG_HOME"/isync/mbsyncrc'
#alias build="source build/envsetup.sh && lunch twrp_cebu-eng && mka clobber && mka -j8 recoveryimage"
alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME"/yarn/config'
alias sudo="doas "
alias sudoedit="doasedit "
#alias obs="swallow flatpak run com.obsproject.Studio"
alias obs="flatpak run com.obsproject.Studio"
alias netbeans='netbeans --userdir "${XDG_CONFIG_HOME}"/netbeans'
alias svn='svn --config-dir $XDG_CONFIG_HOME/subversion'
alias adb='HOME="$XDG_DATA_HOME"/android adb'

# NNN

n ()
{
    # Block nesting of nnn in subshells
    if [ -n $NNNLVL ] && [ "${NNNLVL:-0}" -ge 1 ]; then
        echo "nnn is already running"
        return
    fi

    # The default behaviour is to cd on quit (nnn checks if NNN_TMPFILE is set)
    # To cd on quit only on ^G, remove the "export" as in:
         NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
    # NOTE: NNN_TMPFILE is fixed, should not be modified
    #export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"

    # Unmask ^Q (, ^V etc.) (if required, see `stty -a`) to Quit nnn
    # stty start undef
    # stty stop undef
    # stty lwrap undef
    # stty lnext undef
    nnn -cdrUAx "$@"

    if [ -f "$NNN_TMPFILE" ]; then
            . "$NNN_TMPFILE"
            rm -f "$NNN_TMPFILE" > /dev/null
    fi
}

# ssh agent

export SSH_AGENT_PID=""
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)

export GPG_TTY=$(tty)
#gpg-connect-agent --homedir $GNUPGHOME updatestartuptty /bye >/dev/null
gpg-connect-agent updatestartuptty /bye >/dev/null


eval "$(starship init bash)"

#autostart WM on tty1

#if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then exec sx ~/.config/sx/sxrc 2> /tmp/X.log; fi
#if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then exec Hyprland > /tmp/X.log 2>&1; fi
