#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

##---i3-scratchpad---##
bspc rule -a dropdown sticky=on state=floating hidden=on

st -c dropdown -e mocp &

##--bspwm-rules---##
bspc rule -a Zathura state=tiled follow=on
##---Auto-start---##

nm-applet &
pasystray &
blueman-applet &
$HOME/.config/polybar/launch.sh &
feh --no-fehbg --bg-scale ~/Pictures/colorsch/nord.png &

###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier lock
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus any

bspc config focus_follows_pointer false
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color	"4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#406ea5"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color "#dd2727"

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


