source ~/.config/nvim/plugins.vim
source ~/.config/nvim/airline.vim
source ~/.config/nvim/basics.vim
source ~/.config/nvim/color.vim
"source ~/.config/nvim/deoplete.vim
source ~/.config/nvim/fern.vim
source ~/.config/nvim/keybinds.vim
"source ~/.config/nvim/netrw.vim
source ~/.config/nvim/spell.vim
source ~/.config/nvim/vimwiki.vim
source ~/.config/nvim/complete.vim
source ~/.config/nvim/tex.vim
